apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-deployer-api
  namespace: app-deployer
  labels:
    app.kubernetes.io/name: app-deployer
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-deployer
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-deployer-worker
  namespace: app-deployer
  labels:
    app.kubernetes.io/name: app-deployer
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-deployer
      app.kubernetes.io/component: worker
