apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-deployer-base

namespace: app-deployer

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: app-deployer-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - service.yaml
  - istio.yaml

commonLabels:
  app.kubernetes.io/name: app-deployer

images:
  - name: app-deployer
    newName: gcr.io/YOUR_PROJECT/app-deployer
    newTag: latest
