apiVersion: v1
kind: Namespace
metadata:
  name: app-deployer
  labels:
    app.kubernetes.io/name: app-deployer
    app.kubernetes.io/part-of: app-deployer-platform
    # Enable Istio sidecar injection
    istio-injection: enabled
